### ISSUE TITLE
file.read() lost its timeout parameter between 3.1.2 and 3.2.0

### ISSUE THREAD

**Issue by adelie93** [zhaojh329/lua-eco#12]
## Environment

* arch: ARM
* os: OpenWrt 24
* version: 3.2.0

## Description

The eco `file.read()` function had a timeout parameter that was helpful for polled IO. It has been removed.
What is the recommended strategy to replace this?

**Comment by zhaojh329** [comment]
https://github.com/zhaojh329/lua-eco/blob/master/examples/bufio.lua
https://github.com/zhaojh329/lua-eco/blob/master/examples/termios.lua

**Comment by adelie93** [comment]
Thanks, very helpful. Using `bufio :read()` worked as a replacement.
