### ISSUE TITLE
server.lua example no longer working because of bufio

### ISSUE THREAD

**Issue by frankyjohnston** [zhaojh329/lua-eco#7]
/usr/local/lib/lua/5.3/eco/bufio.lua:239: "reader" must be a table
when running example server.lua
The c code seems to expect a number from getfd but 
this happens:
```function M.new(reader, size)
    if type(reader) ~= 'table' then
        error('"reader" must be a table')
    end
```

**Comment by zhaojh329** [comment]
The bufio.lua has been removed.
You need remove `/usr/local/lib/lua/5.3/eco/bufio.lua` installed previously.

**Comment by frankyjohnston** [comment]
Thanks, that fixed it.  Sorry my mistake for not doing a clean up of old version.
Thanks for the great work.

On Sun, 07 Jul 2024 05:43:41 -0700
Jianhui Zhao ***@***.***> wrote:

> The bufio.lua has been removed.
> You need remove `/usr/local/lib/lua/5.3/eco/bufio.lua` installed previously.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/zhaojh329/lua-eco/issues/7#issuecomment-2212437589
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


--
